version: '3.8'

services:
  frontend:
    build:
      context: client
      dockerfile: dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: server
      dockerfile: dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./server/.env:/app/.env
